// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwuqLCs5kdCPZgQPVDJgeMBQE5FBo47qI',
    appId: '1:294855375854:web:a633a3abc33be99d432cff',
    messagingSenderId: '294855375854',
    projectId: 'my-first-firebase-pro-a6c8a',
    authDomain: 'my-first-firebase-pro-a6c8a.firebaseapp.com',
    storageBucket: 'my-first-firebase-pro-a6c8a.firebasestorage.app',
    measurementId: 'G-320H5BJHTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFjjuwlgpSACv92k30FiFFcl25_36iC6c',
    appId: '1:294855375854:android:f9fa9e1d88c94f9d432cff',
    messagingSenderId: '294855375854',
    projectId: 'my-first-firebase-pro-a6c8a',
    storageBucket: 'my-first-firebase-pro-a6c8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_EO0vCsYjpEJ-zfUSJnmsq-cqBGyO2U',
    appId: '1:294855375854:ios:02ee28700f7dc78c432cff',
    messagingSenderId: '294855375854',
    projectId: 'my-first-firebase-pro-a6c8a',
    storageBucket: 'my-first-firebase-pro-a6c8a.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFirebasePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB_EO0vCsYjpEJ-zfUSJnmsq-cqBGyO2U',
    appId: '1:294855375854:ios:02ee28700f7dc78c432cff',
    messagingSenderId: '294855375854',
    projectId: 'my-first-firebase-pro-a6c8a',
    storageBucket: 'my-first-firebase-pro-a6c8a.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFirebasePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwuqLCs5kdCPZgQPVDJgeMBQE5FBo47qI',
    appId: '1:294855375854:web:37336f313adca11e432cff',
    messagingSenderId: '294855375854',
    projectId: 'my-first-firebase-pro-a6c8a',
    authDomain: 'my-first-firebase-pro-a6c8a.firebaseapp.com',
    storageBucket: 'my-first-firebase-pro-a6c8a.firebasestorage.app',
    measurementId: 'G-C5T4TQ62XF',
  );
}
